### PR TITLE
Bump to 0.3.0.

### PR DESCRIPTION
**Pull request by roryk**
See https://github.com/conda-forge/r-viridis-feedstock/pull/1

### CODE REVIEW

**Comment by roryk** [comment]
Hi @bgruening, 

This should be all set if you have the merge power. I have a commit here: https://github.com/roryk/r-viridis-feedstock/commit/8517a7cedce5ad7763d8bea40e22bd66de960804 which updates r-viridis to 0.5.1 which I'll open once this is merged in.

**Comment by bgruening** [comment]
I can, but lets give @croth1 a chance.

**Comment by croth1** [comment]
thanks @roryk, looks good! 
@bgruening feel free to merge PR in all r-feedstocks I am currently the only maintainer. These are from the very beginning of the bioconda r migration to conda-forge. I am not a heavy r user myself, so I am not very active updating them.

**Comment by roryk** [comment]
Thanks all!

**Pull request merged**
